### ISSUE TITLE
Publish the Gridcoin "4.0.0.1" General Public Roadmap article

### ISSUE THREAD

**Issue by tomasbrod** [gridcoin-community/Gridcoin-Tasks#181]
The article is in preparation on private Etherpad. Special people can get access via Slack.

* [x] Collect data
* [x] Start writing
* [x] Finish the article
* [x] Thank contributors
* [x] Proofread
* [x] append "Multisig" for trustworthiness
* [x] Publish on Steemit
* [x] Link on Twitter
* [x] Link on Reddit
* [ ] Link on CCT forum
