### ISSUE TITLE
Gridcoin Project Process Listing v2

### ISSUE THREAD

**Issue by G-UK** [gridcoin-community/Gridcoin-Tasks#213]
Current Process (v1) -- #194 
De-Listing Process Discussion -- #201 

The Proposal:
[Gridcoin Project Listings v2.docx](https://github.com/gridcoin-community/Gridcoin-Tasks/files/1786969/Gridcoin.Project.Listings.v2.docx)
Calculation Spreadsheet:
[Whitelist 06-03-18.zip](https://github.com/gridcoin-community/Gridcoin-Tasks/files/1786848/Whitelist.06-03-18.zip)
Listing Reasoning (WIP):
[Gridcoin Project Listings Reasoning.docx](https://github.com/gridcoin-community/Gridcoin-Tasks/files/1787031/Gridcoin.Project.Listings.Reasoning.docx)

Change Summary for v2:
- Addition of De-Listing Process from #201 
- Change of all Polls to require both greater than 50% vote share by number of voters and greater than 50% vote share by Mag & Balance weight.
  - Attempt to make votes fairer.
- Addition of 48 hour timeout for a project when it is Greylisted
  - To prevent projects bouncing in and out of the Greylist, once Greylisted they will remain so for a minimum of 48hrs
- Addition of Requirement for project reported Recent Average Compute Power to be greater than 2500GFlops where statistic is available.
  - "Soucefinder" fix, attempt to weed out very low compute projects.

To-Do List:

- [ ] Document explaning logic behind each item in the Process
- [ ] Process inclusion to Blue Paper
- [ ] Publication of Greylist on https://gridcoin.us
- [ ] Creation of auto-updated Greylist with stats scrape on https://www.griscoinstats.eu

**Comment by NeuralMiner** [comment]
```50% vote share by number of voters```
This is far too easy to manipulate.

**Comment by G-UK** [comment]
I know, I'm hoping the discussion in economics can agree something better and I am willing to follow whatever ends up being agreed for CBR.

**Comment by tomasbrod** [comment]
I do not support removing projects from grey/white-list unless it is absolutely necessary or requested by vote.
Security suspicion should automatically force project out of white-list as fast as possible.
Being in grey-list for 60 days should not be a reason to de-list a project.

I would like to see the condition results as a list of flags. Then the final whitelist status will be given by Boolean function. Like:
F := (WAS=green) and (stats_export_T < 2d) not admin_denied and ...

**Comment by grctest** [comment]
>  Security suspicion should automatically force project out of white-list as fast as possible.

What classifies as a security suspicion? PG GRC security rant could have triggered this, yet it's a subjective analysis not conclusive evidence of harm (say malware).

**Comment by tomasbrod** [comment]
Security suspicion is anything that affects security of cruncher computer, security of the network, or attempts to cheat the credits.
